insert into RAMO_ATIVIDADE (id, DESCRICAO) values (1, 'Distribuição de alimentos');
insert into RAMO_ATIVIDADE (id, DESCRICAO) values (2, 'Telecomunicações');
insert into RAMO_ATIVIDADE (id, DESCRICAO) values (3, 'Vestuário');
insert into RAMO_ATIVIDADE (id, DESCRICAO) values (4, 'Lavanderia');
insert into RAMO_ATIVIDADE (id, DESCRICAO) values (5, 'Gráfica');
insert into RAMO_ATIVIDADE (id, DESCRICAO) values (6, 'Mecânica');
insert into RAMO_ATIVIDADE (id, DESCRICAO) values (7, 'Turismo');
insert into RAMO_ATIVIDADE (id, DESCRICAO) values (8, 'Saúde');
insert into RAMO_ATIVIDADE (id, DESCRICAO) values (9, 'Educação');
insert into RAMO_ATIVIDADE (id, DESCRICAO) values (10, 'Lazer');

insert into EMPRESA (id, CNPJ, NOME_FANTASIA, RAZAO_SOCIAL, tipo, DATA_FUNDACAO, RAMO_ATIVIDADE_ID) values (1, '70.311.193/0001-87', 'Mercado do João', 'João Mercado e Distribuidor de Alimentos Ltda', 'LTDA', '2009-03-02', 1);
insert into EMPRESA (id, CNPJ, NOME_FANTASIA, RAZAO_SOCIAL, tipo, DATA_FUNDACAO, RAMO_ATIVIDADE_ID) values (2, '52.822.994/0001-25', 'Fale Mais', 'Fale Mais Telecom S.A.', 'SA', '1997-12-10', 2);
insert into EMPRESA (id, CNPJ, NOME_FANTASIA, RAZAO_SOCIAL, tipo, DATA_FUNDACAO, RAMO_ATIVIDADE_ID) values (3, '41.952.519/0001-57', 'Maria de Souza da Silva', 'Maria de Souza da Silva', 'MEI', '2014-10-15', 3);
insert into EMPRESA (id, CNPJ, NOME_FANTASIA, RAZAO_SOCIAL, tipo, DATA_FUNDACAO, RAMO_ATIVIDADE_ID) values (4, '16.134.777/0001-89', 'Gomes Inovação', 'José Fernando Gomes EIRELI ME', 'EIRELI', '2009-03-02', 4);
insert into EMPRESA (id, CNPJ, NOME_FANTASIA, RAZAO_SOCIAL, tipo, DATA_FUNDACAO, RAMO_ATIVIDADE_ID) values (5, '16.134.777/0001-89', 'Gomes Inovação', 'José Fernando Gomes EIRELI ME', 'EIRELI', '2009-03-02', 4);
insert into EMPRESA (id, CNPJ, NOME_FANTASIA, RAZAO_SOCIAL, tipo, DATA_FUNDACAO, RAMO_ATIVIDADE_ID) values (6, '16.134.777/0001-89', 'Gomes Inovação', 'José Fernando Gomes EIRELI ME', 'EIRELI', '2009-03-02', 4);
insert into EMPRESA (id, CNPJ, NOME_FANTASIA, RAZAO_SOCIAL, tipo, DATA_FUNDACAO, RAMO_ATIVIDADE_ID) values (7, '16.134.777/0001-89', 'Gomes Inovação', 'José Fernando Gomes EIRELI ME', 'EIRELI', '2009-03-02', 4);
insert into EMPRESA (id, CNPJ, NOME_FANTASIA, RAZAO_SOCIAL, tipo, DATA_FUNDACAO, RAMO_ATIVIDADE_ID) values (8, '16.134.777/0001-89', 'Gomes Inovação', 'José Fernando Gomes EIRELI ME', 'EIRELI', '2009-03-02', 4);
insert into EMPRESA (id, CNPJ, NOME_FANTASIA, RAZAO_SOCIAL, tipo, DATA_FUNDACAO, RAMO_ATIVIDADE_ID) values (9, '16.134.777/0001-89', 'Gomes Inovação', 'José Fernando Gomes EIRELI ME', 'EIRELI', '2009-03-02', 4);
insert into EMPRESA (id, CNPJ, NOME_FANTASIA, RAZAO_SOCIAL, tipo, DATA_FUNDACAO, RAMO_ATIVIDADE_ID) values (10, '16.134.777/0001-89', 'Gomes Inovação', 'José Fernando Gomes EIRELI ME', 'EIRELI', '2009-03-02', 4);
insert into EMPRESA (id, CNPJ, NOME_FANTASIA, RAZAO_SOCIAL, tipo, DATA_FUNDACAO, RAMO_ATIVIDADE_ID) values (11, '16.134.777/0001-89', 'Gomes Inovação', 'José Fernando Gomes EIRELI ME', 'EIRELI', '2009-03-02', 4);
insert into EMPRESA (id, CNPJ, NOME_FANTASIA, RAZAO_SOCIAL, tipo, DATA_FUNDACAO, RAMO_ATIVIDADE_ID) values (12, '70.311.193/0001-87', 'Mercado do João', 'João Mercado e Distribuidor de Alimentos Ltda', 'LTDA', '2009-03-02', 1);